const mongoose = require("mongoose");
const Company = require("../models/company.js");

mongoose.connect("mongodb://localhost:27017/openbank", {
  useNewUrlParser: true,
  useUnifiedTopology: true
});

// Создание компании в БД
async function createCompany() {
  await Company.create({
    companyName: this.companyName,
    projectName: this.projectName,
    industry: this.industry,
    projectDuration: this.projectDuration,
    yearOfFoundation: this.yearOfFoundation,
    investments: this.investments,
    netDebt: this.netDebt,
    description: this.description,
    IRR: this.IRR,
    NPV: this.NPV,
    IRRTV: this.IRRTV,
    NPVTV: this.NPVTV,
    DPBP: this.DPBP,
    TV: this.TV,
    market: this.market,
    sector1: this.sector1,
    sector2: this.sector2,
    sector3: this.sector3,
    sector4: this.sector4,
    competitor1: this.competitor1,
    competitor2: this.competitor2,
    competitor3: this.competitor3,
    competitor4: this.competitor4,
    competitor5: this.competitor5,
    trend1: this.trend1,
    trend2: this.trend2,
    trend3: this.trend3,
    trend4: this.trend4,
    trend5: this.trend5,
    revenue: this.revenue,
    revenue1: this.revenue1,
    revenue2: this.revenue2,
    revenue3: this.revenue3,
    revenue4: this.revenue4,
    revenue5: this.revenue5,
    costPrice: this.costPrice,
    cost1: this.cost1,
    cost2: this.cost2,
    cost3: this.cost3,
    cost4: this.cost4,
    KiAUR: this.KiAUR,
    EBTDA: this.EBTDA,
    profitabilityEBTDA: this.profitabilityEBTDA,
    depreciation: this.depreciation,
    EBT: this.EBT,
    interest: this.interest,
    incomeTax: this.incomeTax,
    netProfit: this.netProfit,
    capitalExpenditures: this.capitalExpenditures,
    projectInvestments: this.projectInvestments,
    projectNetDebt: this.projectNetDebt,
    cashFlow: this.cashFlow,
    FCFF: this.FCFF,
    index1: this.index1,
    index2: this.index2,
    index3: this.index3,
    index4: this.index4
  });
}

module.exports = createCompany;

// async function seed() {
//   for (let i = 0; i < 5; i++) {
//     let company1 = new Company({
//       companyName: `companyName ${i}`,
//       projectName: `projectName ${i}`,
//       industry: `industry ${i}`,
//       projectDuration: `projectDuration ${i}`,
//       yearOfFoundation: i,
//       investments: i,
//       netDebt: i,
//       description: `description ${i}`,
//       IRR: i,
//       NPV: i,
//       IRRTV: i,
//       NPVTV: i,
//       DPBP: i,
//       TV: i,
//       market: [`Array${i}`],
//       sector1: [`Array${i}`],
//       sector2: [`Array${i}`],
//       sector3: [`Array${i}`],
//       sector4: [`Array${i}`],
//       competitor1: `competitor1 ${i}`,
//       competitor2: `competitor2 ${i}`,
//       competitor3: `competitor3 ${i}`,
//       competitor4: `competitor4 ${i}`,
//       competitor5: `competitor5 ${i}`,
//       trend1: `trend1 ${i}`,
//       trend2: `trend2 ${i}`,
//       trend3: `trend3 ${i}`,
//       trend4: `trend4 ${i}`,
//       trend5: `trend5 ${i}`,
//       revenue: [`Array${i}`],
//       revenue1: [`Array${i}`],
//       revenue2: [`Array${i}`],
//       revenue3: [`Array${i}`],
//       revenue4: [`Array${i}`],
//       revenue5: [`Array${i}`],
//       costPrice: [`Array${i}`],
//       cost1: [`Array${i}`],
//       cost2: [`Array${i}`],
//       cost3: [`Array${i}`],
//       cost4: [`Array${i}`],
//       KiAUR: [`Array${i}`],
//       EBTDA: [`Array${i}`],
//       profitabilityEBTDA: [`Array${i}`],
//       depreciation: [`Array${i}`],
//       EBT: [`Array${i}`],
//       interest: [`Array${i}`],
//       incomeTax: [`Array${i}`],
//       netProfit: [`Array${i}`],
//       capitalExpenditures: [`Array${i}`],
//       projectInvestments: [`Array${i}`],
//       projectNetDebt: [`Array${i}`],
//       cashFlow: [`Array${i}`],
//       FCFF: [`Array${i}`],
//       index1: i,
//       index2: i,
//       index3: i,
//       index4: i
//     });
//     await company1.save();
//   }
// }
// seed();
